### PR TITLE
Configurable screensaver

### PR DESCRIPTION
**Pull request by dylwhich**

### CODE REVIEW

**Comment by AEFeinstein** [comment]
Can you shuffle the menu options so that there's enough room for "Screensaver" rather than "Screensave"?

**Comment by dylwhich** [comment]
Oh, right, that totally works. How's this?

image

**Comment by dylwhich** [comment]
Done!

**Comment by dylwhich** [comment]
I kinda thought it would be weird to move Mic Gain away from the Music/SFX options, but now it's with all the other 0-7 options so it still seems kinda consistent

**Comment by AEFeinstein** [comment]
Good enough for me!

**Review by AEFeinstein — APPROVED** [review]

**Pull request merged**
