### PR TITLE
Button Edge Case Fixes

### PR DESCRIPTION
**Pull request by dylwhich**
If two buttons are pressed at the exact same time, currently the mode button callback gets passed a `buttonBit_t` that doesn't match any of the enum values because it's actually two buttons. This change detects that and simulates two sequential button events with the appropriate state and down value as though they were handled sequentially. The loop will only loop as many times as there are buttons changed.

### CODE REVIEW

**Comment by dylwhich** [comment]
okay that definitely made start/select break, let me fix that now

**Comment by dylwhich** [comment]
nevermind, the header weirdness in the emu strikes again

**Comment by AEFeinstein** [comment]
This hadn't been a problem with interrupt-driven buttons, but it can be with polling. Let me take a good look at this, its a bit more critical than most code.

**Comment by dylwhich** [comment]
Yeah, that's fair. Actually should I move that into its own branch and take it out of here?

**Review by AEFeinstein — APPROVED** [review]

**Comment by AEFeinstein** [comment]
Too late

**Pull request merged**
