### PR TITLE
π-cross tentative fill

### PR DESCRIPTION
**Pull request by maxwelllc**
With some help from Bryce, I've added tentative fill marks per issue #294.

The implementation I chose for this may seem a bit less intuitive (I'm using a separate `bool tentativeMarks[][]` which is saved to NVS with a new key), but this allows for straightforward backward compatibility with 1.0 saves. 

Other notable design choices that are probably worth thinking about:
- I intentionally prevent you from placing a tentative mark over a non-empty space. However, you can place other marks over a tentative mark
- Hold-and-move is similar to the other space types, but with a caveat:
	- If you press and hold the tentative mark button (any touch input) while hovering a filled or X'd square and then move the cursor, it will tentative mark any other empty spaces you come over without overwriting any other filled spaces. This seemed the most intuitive to me, but I'm open to feedback
- The mark is always a 3-pixel stroke circle, unaffected by resizing. I figure this is best for visibility reasons (Although I'm not super confident about the color I picked)

image
image

### CODE REVIEW

**Review by AEFeinstein — APPROVED** [review]
Looks good from a code perspective. I'll wait for @hunterdyar to give the 👍 from a game perspective (and code too, I suppose) before merging.

**Comment by hunterdyar** [comment]
I'm on the road with a mac laptop and no environment to test but:

- I like the feature, I like that it's with the touch inputs, which is nice and simple to teach or ignore. it's a nice-to-have for players who use it, and helps with accessibility - like helping those who struggle with vision or counting. 
- Unable to test myself, can we confirm how pressing touch+other buttons at the same time, during first frame, and during DAS (hold + move) and so on work? I think its at the end of the input, and so the toggle/setMarks code should concede priority to other input (probably the right way to work) if they happen on the same frame. Because the input code isn't as clean as I would like, we can't simply escape out of it when valid input happens (because of error flashing and DAS timer stuff).

Can't approve until colors get worked out:
- Does changing the "X or Fill" preference setting affect the design? Looks like it uses emptySpaceCol, so it's always going to be orange. The mark-empty will be either red or full orange depending on the setting, when both are orange that will be pretty bad.
- Pick a color that's tonally grey. I think we haven't touched purples or greens, I'd go color over just grey, so long as some white dot inside the circle is always visible. Slap a colorblind simulator on the emulator and test?
- On a similar note, I don't know about it not respecting the scaling. Looks good in the screenshots, and it should always be nice and visible, and notably circular-ish. Have we tested on 15x15 levels that have really long clues? I know i cut the worst one of those from the build, but I think there's at least one 15x15 that's irksome in scale, one of the latest ones, so lets make sure to test that.

Other code stuff and saving i'll concede to @AEFeinstein expertise, as I'm just glancing over it all on the road (thanks for screenshots!)

I would be happy to approve this for now, with colors sorted, but keeping in mind that on a possible future refactor, I would want to fold this property in with the space enum, and simplify everything.  A current solution that respects users existing save data if upgrading the swadge is worth it.

**Comment by Brycey92** [comment]
> Unable to test myself, can we confirm how pressing touch+other buttons at the same time, during first frame, and during DAS (hold + move) and so on work? I think its at the end of the input, and so the toggle/setMarks code should concede priority to other input (probably the right way to work) if they happen on the same frame. Because the input code isn't as clean as I would like, we can't simply escape out of it when valid input happens (because of error flashing and DAS timer stuff).

The touch control works similarly to other buttons when pressing multiple buttons at once. Sometimes, one will take priority and get dragged along with DAS. Sometimes, the tentative mark will take priority in the current cell and DAS will clear any fill/empty marks it goes over after the first cell. Dragging a deletion of fill/empty marks will never delete a tentative mark. Dragging actual fill/empty marks or placing individual marks will always overwrite a tentative mark. A tentative mark will never overwrite a fill/empty mark.

**Comment by Brycey92** [comment]
> Does changing the "X or Fill" preference setting affect the design? Looks like it uses emptySpaceCol, so it's always going to be orange. The mark-empty will be either red or full orange depending on the setting, when both are orange that will be pretty bad.

No, the design is always a circle. I find it more difficult to tell the difference between Xs and circles, to be honest, since it's easier to tell a big square from a smaller circle than it is to tell a smaller reddish shape from a smaller orange shape.

**Comment by Brycey92** [comment]
> On a similar note, I don't know about it not respecting the scaling. Looks good in the screenshots, and it should always be nice and visible, and notably circular-ish. Have we tested on 15x15 levels that have really long clues? I know i cut the worst one of those from the build, but I think there's at least one 15x15 that's irksome in scale, one of the latest ones, so lets make sure to test that.

I tested on the last puzzle, where the Xs turn into small red squares, and the tentative marks seem to be the same size as in other 15x15 puzzles, but are off-center to the top left.

**Comment by maxwelllc** [comment]
I've just pushed some tweaks based on your suggestions.

1. I've changed the circles to squares. This is because I saw no preexisting function to draw circles with even number diameters, which is necessary to fix the offset bug Bryce mentioned. The plotCircleFilled function can only do odd and the plotEllipse functions introduce a weird graphical artifact (Will be opening a separate bug issue). I figured this was for the best anyways, especially given the feedback that the X's and O's look similar on the big puzzles.
2. The width is now relative to the box size - I arbitrarily chose 1/5th the box size since it looked good to me.
3. Picked a shade of purple that seemed good. I ran it through this [colorblind simulator](https://www.color-blindness.com/coblis-color-blindness-simulator/) and it seemed like it would be usable. The only issue I saw was that it is similar to the cursor outline when viewing with protanopia, but the whitespace in the middle should (hopefully) make it a non-issue. Let me know what you think. 

A note on input priority - as Bryce mentioned, tentative marks never overwrite other marks. It also concedes priority during DAS, such that If you press touch input and another button at the same time, the other input always wins. 

Let me know what you think!

image
image
image


Example of protanopia. I'm not too worried about this, but tell me if I should be.
image

**Comment by hunterdyar** [comment]
Changes looks good to me. Thanks for including screenshots in comments. Nice work!

**Review by AEFeinstein — APPROVED** [review]

**Pull request merged**
