### PR TITLE
No stress tris for the masses

### LINKED ISSUE #318: Tiltrads: Chill mode
I saw "no stress tris" in some #defines and such, and thought it would be cool to give very casual gamers options in how they want to play the game. High-score recording would of course either be disabled or separated

### PR DESCRIPTION
**Pull request by Brycey92**
Please make sure I implemented this as you would want! I wasn't sure about positioning of controls text on the title screen, so I can shift that around if you want.

Closes #318

### CODE REVIEW

**Review by jt-moriarty — CHANGES_REQUESTED** [review]
Ok, now that I've had a chance to check this out, I have a couple concerns before I'd be comfortable approving this:
1. I think the way the text is implemented on the main menu is incorrect, the no-stress-tris control texts should be below the normal options.
2. Rather than different buttons for no-stress-tris game and score screens, I think it makes more sense for a single button to toggle no-stress-tris from the main menu, and then that toggle controls what score screen and game screen the player enters.
3. I'm not sure how much I like no-stress-tris being a user-exposed term, it was always a private joke, just calling it "no-stress" mode or no-stress tiltrads might be better.
I can take a crack at making these changes Monday night if that's still within our window for changes.

**Comment by AEFeinstein** [comment]
Good until the 15th: https://magfest.slack.com/archives/C6FNXU6KX/p1669868708663459

**Comment by Brycey92** [comment]
Did the merge, solved the conflicts

**Comment by Brycey92** [comment]
I took care of the reordering and renaming, but I wasn't sure how you wanted the control change implemented.

**Review by jt-moriarty — APPROVED** [review]
Tweaked it a little bit towards what I was describing. I'm good with this if it still meets expectations.

**Comment by Brycey92** [comment]
Looks good to me, and still works properly in testing too!

**Review by AEFeinstein — APPROVED** [review]

**Pull request merged**
