### PR TITLE
#106 Fix pi-cross filled-in hint detection

### PR DESCRIPTION
**Pull request by dylwhich**

### CODE REVIEW

**Comment by AEFeinstein** [comment]
@hunterdyar can you review this please?

**Comment by dylwhich** [comment]
Now that it's not 3am, some details:

I changed the algorithm for `hintIsFilledIn()` to build an array counting the length of each filled in segment in the row/column. I also combined the separate row/column logic into a single weird for loop, but if it's not performant / is too confusing, I can split that into two branches.

In the second loop, I ran into an issue where sometimes, the hint's first hint value was 0, e.g. if the hint displayed in the game is `1 2`, the hint->hints array would be `{0, 1, 2, 0, 0, 0, 0, 0}` instead of what I expected, `{1, 2, 0, 0, 0, 0, 0, 0}`. So I added logic to skip the first hint if it's 0, and then compare the segment lengths to the hints offset by 1. It works perfectly for every puzzle I've tried, but I'm not sure if there's a better solution or just something I'm missing about how the hints array is constructed.

**Review by hunterdyar — APPROVED** [review]
There are a few things to consider, i'd be happy to chat about these things some time.

The first is if this is the behavior we want. If a line is 'complete' in blocks, but not marked empty, I agree that it would be good to give the user feedback of this - and that it is likely what a user expects (so pull request: approved)... Although. The design goals of the fading is to direct the user where focus attention while solving. Marking the empties is often necessary for solving a different line elsewhere, so I want to encourage them that there is information to be found in 'completed' lines. Perhaps a solution is multiple levels of fade, and we have it both ways. Maybe Dac has an opinion here that's stronger than mine.

The second thing to consider is that this logic of building out clues from a given line is already implemented, and we should probably generalize the functions into one function, something like "ArrayFromLine". One piece of code/logic is preferred, rather than two separate places that have to come to the same conclusion. (in fact, that first 0 in the array is a just a low-priority bug; already one piece of logic has to account for an oddity of the other).

We only need to check if the changes happen on the rows that actually changed, which is an optimization that the code needs in a few place (although it apparently runs fine on hardware, and the game isn't real-time, so we have some wiggle room). For now its fine because it only checks when there is a change, not every frame.

Lastly, if we do check if the entered clues match the existing clues, we can use this information for puzzle-complete validation. The current system - just comparing the spaces - only works if a puzzle is assured to have a unique solution. It would be better to compare clues, just in case a puzzle doesn't have a unique solution. if we are doing this logic anyway, It would not be an overhead to use it for validation. 

To note.... A properly designed puzzle should have a unique solution, so it shouldn't matter, hence the choice of the current vs. commented out logic in picrossCheckLevel.

**Comment by AEFeinstein** [comment]
@dylwhich is dylwhich on slack and @hunterdyar is blooper if you wanna chat there too.

**Pull request merged**
