### PR TITLE
Tiltrads changes

### PR DESCRIPTION
**Pull request by Brycey92**
You can click on the 2 commits with actual code changes to review those

### CODE REVIEW

**Comment by AEFeinstein** [comment]
Ah yes, its much clearer if you ignore comments one. I'll still wait for @jt-moriarty's review
* https://github.com/AEFeinstein/Super-2023-Swadge-FW/pull/195/commits/fafcdcac5d6a412f352ae88ddfe48ed58b59191d
* https://github.com/AEFeinstein/Super-2023-Swadge-FW/pull/195/commits/9e9749c04e9bed866c91a61724460ad1b3edcf69

**Comment by AEFeinstein** [comment]
But to sum it up
* The `SELECT` button now shows scores rather than `LEFT`
* `SELECT` to exit was removed
* `BTN_A` can now start the game, same as `START`

**Review by jt-moriarty — APPROVED** [review]
These feel like good changes, I'm assuming modes don't need a way to exit back to main menu anymore? I also went ahead and resolved the conflict in main related to the accel tweaks.

**Comment by jt-moriarty** [comment]
Also rolled in a fix for a niche bug where a tetrad that was hard dropped on the same frame as a game over would not render.

**Comment by Brycey92** [comment]
@jt-moriarty you're correct, the firmware now has baked in start+select exit, which is caught before all modes' button callbacks afaik

**Comment by AEFeinstein** [comment]
That's correct. Start+Select is caught by the system and is capable of
exiting from any mode or screen.

**Pull request merged**
